baseurl = "http://example.org"
title = "Noah Yoshida"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
    title = "Noah Yoshida"
    description = "10 Months into Software Engineering"
    logo = "fa-code"

[[params.social]]
    medium = "github"
    icon = "fa-github"
    link = "https://github.com/noyoshi"


